/**
 * @file The SALES AGENT — Sales Desk's level-2 agent (`agent_level2.js`), moved to Xeon 16/09/2026.
 *
 * It answers like the person on duty: reads the conversation, calls the shop's tools (stock, size
 * chart, policy, bank account) one at a time, then writes ONE message. The rules are the pack's
 * (`IndustryPack.agent`), the data is the landing's; this class only runs the loop.
 *
 * Two guards Desk learned the hard way stay in code, not in the prompt:
 *   - `reviewReply`: a price not seen in a tool result, a link to someone else's site, or a banned
 *     phrase blocks the reply (a model told "never invent a price" still does, now and then);
 *   - a hard step limit and a deadline: a gateway that hangs must not leave the customer waiting.
 * A blocked or failed turn returns `ok: false`, and the caller falls back to the rule engine.
 */

import { emptyShopProfile, type ShopProfile } from "@sp/contract";
import {
  blocksForShop, fillAgentText, redactPII, renderBlocks, renderProfile, stripDiacritics,
  type CommonAgent, type FillValues, type IndustryPack, type PackAgent
} from "@sp/brain";
import type { Clock } from "../support/clock";
import type { Logger } from "../support/logger";
import type { ChatMessage, ChatModelPort } from "./chat-model";

export const MAX_TOOL_STEPS = 6;
export const TURN_DEADLINE_MS = 60_000;
/** How many times a reply blocked by `reviewReply` may be rewritten before the turn fails. */
export const MAX_REVIEW_RETRIES = 2;
/**
 * Tries per model call. A transient gateway failure (empty answer, 5xx, 429, timeout, network) is
 * called again after a growing pause — the gateway usually recovers within seconds.
 */
/** 25/09/2026: two, not four — the gateway breaker (`gateway-breaker.ts`) handles an outage; four retries only made every turn slow. */
export const MODEL_ATTEMPTS = 2;
export const MODEL_BACKOFF_MS = [1000];
/** How far around the customer's own budget an amount may go without a tool source. */
export const BUDGET_BAND = 0.25;
const REVIEW_HINTS = "Gia/so tien chi duoc lay tu ket qua cong cu GOI TRONG LUOT NAY (gia trong tin cu cua PAGE khong tinh) — goi lai cong cu hoac bo con so do. Link chi lay tu ket qua cong cu. Viet lai va tra {\"reply\":\"...\"}.";
/** Tool results are cut before they reach the model (Desk's limits). */
const STOCK_RESULT_CHARS = 8000;
const TEXT_RESULT_CHARS = 6000;

/**
 * One line of the conversation as the agent reads it, oldest first; the last one is the message to answer.
 *
 * `who` carries Desk's three page labels (v99, 16/09/2026): a sentence the BOT wrote is never a source of
 * truth, a sentence a PERSON typed is, and a page message the landing kept no author for is "khong_ro" —
 * which must NOT be read as a person, or the bot defends its own earlier invention (Desk case Duy Nam 31/08).
 */
export interface HistoryLine {
  who: "khach" | "bot" | "nguoi" | "khong_ro";
  text: string;
  images: number;
  /** ISO time the line was sent; renders as `[dd/mm HH:MM]`, marks photos older than 6 h as "CŨ" and session gaps. */
  at?: string | undefined;
  /** Addresses of the customer's photos on this line, so the model can look them up (`[ANH url=…]`). */
  imageUrls?: string[] | undefined;
  /** A system note pinned to this line, e.g. "KHÁCH ĐANG TRẢ LỜI VÀO TIN …" (Desk P1c). */
  note?: string | undefined;
}

/** A photo older than this is history, not "the picture the customer just sent" (Desk v17, Hana Heng). */
const OLD_IMAGE_MS = 6 * 3600 * 1000;
/** Two lines further apart than this open a new session in the transcript (Desk episode gap). */
const SESSION_GAP_MS = 6 * 3600 * 1000;

/** What the agent may call. Each returns data for the model; errors come back as data too. */
export interface AgentToolBox {
  findStock(args: Record<string, unknown>): Promise<unknown>;
  policy(): Promise<string>;
  bankAccount(): Promise<unknown>;
}

export interface AgentTurn {
  /** Tier 2: the industry's playbook. */
  agent: PackAgent;
  /** Tier 1: the platform's conduct (`loi-chung/`). Absent = an older dossier, replayed as it was. */
  chung?: CommonAgent | undefined;
  /** Tier 3: the shop's profile from its landing. Absent = every field "chưa khai". */
  hoSo?: ShopProfile | null | undefined;
  /** The shop's policy texts, named in the profile section so the model knows what `chinh_sach` holds. */
  chinhSach?: { doiTra: string; ship: string; baoHanh: string } | undefined;
  /**
   * WHAT THE SYSTEM CAN DO THIS TURN, one line each, generated by `systemCapabilities` from the tools
   * the landing opens and the models Xeon has — never written by hand into a pack again (24/09/2026:
   * "chưa xem được ảnh" sat in the shoe pack for three days after Xeon started reading photos).
   */
  nangLuc?: readonly string[] | undefined;
  /** Merchant's public address, for `{site}` and for the link check. */
  site: string;
  /** Shop display name from licence (e.g. "TopRun"). */
  shopName?: string | undefined;
  history: HistoryLine[];
  tools: AgentToolBox;
  /** Phrases that block a reply: the industry's, tier 1's and the shop's, already merged. */
  neverSay?: readonly string[] | undefined;
  /**
   * What the shop taught the AI (Đ7 `training.knowledge`, rendered by `renderKnowledge`): appended to
   * the system prompt. Approved items only; the review queue never reaches the model.
   */
  extraContext?: string | undefined;
  /**
   * Amounts and hosts the turn PROVED before the agent ran (the stock looked up by the pipeline,
   * 25/09/2026): a price the note already states is not an invented price. Older dossiers have none.
   */
  knownAmounts?: readonly number[] | undefined;
  allowedHosts?: readonly string[] | undefined;
  /** The turn's deadline (ms) when the pipeline has less than `TURN_DEADLINE_MS` left for the agent. */
  deadlineMs?: number | undefined;
}

/**
 * A turn WITHOUT its tool box: plain data, so it serialises into the dossier and comes back out
 * for a replay. `tools` is the only live thing in `AgentTurn`, and a replay brings its own.
 */
export type AgentTurnInput = Omit<AgentTurn, "tools">;

export interface AgentTrace {
  step: number;
  tool?: string;
  error?: string;
  /** Đ7 "AI nghĩ gì": the arguments the model chose and what came back. */
  args?: Record<string, unknown>;
  /**
   * EXACTLY what the model was shown as the tool result — not a shortened view. Screens cut it
   * themselves (`ai-desk.ts` takes 300). Cutting it HERE made the dossier unreplayable: a replay
   * fed the model a different result and produced a different answer (21/09/2026).
   */
  result?: string;
  /** The model's raw answer when it could not be parsed as JSON — the reason for the retry. */
  raw?: string;
  /** The reply `reviewReply` refused, kept whole: "why did the bot say that" usually ends here. */
  blocked?: string;
}

/** One answer the model gave, with the model that gave it — a replay needs both. */
export interface ModelAnswer {
  text: string;
  model?: string | undefined;
}

export type AgentOutcome =
  | { ok: true; reply: string; steps: number; trace: AgentTrace[]; modelAnswers: ModelAnswer[] }
  /** `modelDown`: the turn died because the model could not be reached, not because of what it wrote — worth running again. */
  | { ok: false; viSao: string; steps: number; trace: AgentTrace[]; modelAnswers: ModelAnswer[]; modelDown?: boolean };

/** Pulls the first balanced JSON object out of a model answer (models wrap JSON in prose or fences). */
export function parseAgentJson(text: string): Record<string, unknown> | null {
  const cleaned = String(text ?? "").replace(/```json|```/g, "").trim();
  const start = cleaned.indexOf("{");
  if (start < 0) return null;
  let depth = 0;
  let inString = false;
  for (let i = start; i < cleaned.length; i += 1) {
    const ch = cleaned[i];
    if (inString) {
      if (ch === "\\") i += 1;
      else if (ch === "\"") inString = false;
      continue;
    }
    if (ch === "\"") inString = true;
    else if (ch === "{") depth += 1;
    else if (ch === "}") {
      depth -= 1;
      if (depth === 0) {
        try {
          const value = JSON.parse(cleaned.slice(start, i + 1)) as unknown;
          return value !== null && typeof value === "object" && !Array.isArray(value) ? (value as Record<string, unknown>) : null;
        } catch {
          return null;
        }
      }
    }
  }
  return null;
}

/** Money amounts written the ways Vietnamese sellers and customers write them, in VND. */
export function moneyAmounts(text: string): number[] {
  const plain = stripDiacritics(String(text ?? "")).toLowerCase();
  const out: number[] = [];
  // 1.290.000 / 1,290,000 / 1290000. Not a phone, an account number or a code: plain digits only
  // 5-8 long, no leading 0, not glued to letters ("JP9252", "TR12345") — except the currency: "đ"
  // becomes "d" once accents are stripped, so "3.290.000đ" must still count.
  for (const m of plain.matchAll(/(?<![\w.,])(\d{1,3}(?:[.,]\d{3})+|[1-9]\d{4,7})(?![.,]?\d)(?!(?!d\b|vnd\b|dong\b)[a-z])/g)) {
    out.push(Number(m[1]!.replace(/[.,]/g, "")));
  }
  // 1tr2 / 1 tr / 1,2 trieu / 1.5 trieu
  for (const m of plain.matchAll(/(\d+)(?:[.,](\d+))?\s*(?:tr|trieu)(\d)?(?![a-z])/g)) {
    const whole = Number(m[1]);
    const fraction = m[2] ?? m[3] ?? "";
    out.push(Math.round((whole + (fraction ? Number(`0.${fraction}`) : 0)) * 1_000_000));
  }
  // 890k / 890 nghin / 890 ngan — and "1.350k" (24/09/2026): the model writes 1.350.000đ that way, and
  // reading only "350k" out of it blocked a correct price as "gia_khong_nguon".
  for (const m of plain.matchAll(/(\d{1,3}(?:[.,]\d{3})+|\d+)\s*(?:k|nghin|ngan)(?![a-z])/g)) out.push(Number(m[1]!.replace(/[.,]/g, "")) * 1000);
  return out;
}

/** Every number in a JSON-ish value, for the "price has a source" check. */
function numbersIn(value: unknown, into: Set<number>): void {
  if (typeof value === "number" && Number.isFinite(value)) { into.add(value); return; }
  if (typeof value === "string") { for (const n of moneyAmounts(value)) into.add(n); return; }
  if (Array.isArray(value)) { for (const v of value) numbersIn(v, into); return; }
  if (value !== null && typeof value === "object") for (const v of Object.values(value)) numbersIn(v, into);
}

function hostOf(url: string): string {
  try { return new URL(url).host.toLowerCase(); } catch { return ""; }
}

export interface ReviewInput {
  reply: string;
  /** Numbers seen in tool results and the policy. */
  knownAmounts: ReadonlySet<number>;
  /**
   * Amounts the CUSTOMER wrote (their budget). Talking around a budget is not inventing a price:
   * "1tr2" from the customer licenses "tầm 1tr–1tr2" (16/09/2026), so a band of ±25% is allowed.
   */
  budgetAmounts?: readonly number[] | undefined;
  /** Hosts a link may point to. */
  allowedHosts: ReadonlySet<string>;
  neverSay?: readonly string[] | undefined;
}

/** `null` when the reply may go out, otherwise the reason it may not. */
export function reviewReply(input: ReviewInput): string | null {
  const reply = input.reply.trim();
  if (reply === "") return "tra_loi_rong";
  const plain = stripDiacritics(reply).toLowerCase();
  for (const phrase of input.neverSay ?? []) {
    if (phrase.trim() !== "" && plain.includes(stripDiacritics(phrase).toLowerCase())) return `cau_cam: ${phrase}`;
  }
  // A money amount below 10.000đ is not a price (sizes, days, percentages written with k...).
  for (const amount of moneyAmounts(reply)) {
    if (amount < 10_000 || input.knownAmounts.has(amount)) continue;
    if ((input.budgetAmounts ?? []).some((budget) => Math.abs(amount - budget) <= budget * BUDGET_BAND)) continue;
    return `gia_khong_nguon: ${amount}`;
  }
  for (const m of reply.matchAll(/https?:\/\/[^\s)"'<>]+/g)) {
    const host = hostOf(m[0]);
    if (!input.allowedHosts.has(host)) return `link_la: ${host || m[0]}`;
  }
  // A size stated as certain ("đi size 42 là vừa") without a hedge: the industry rule says never
  // promise a fit (24/09/2026 evaluation, kb-15 / kb2-15). Hedged wording passes.
  if (/size\s*\d[\d\s/.,]*\s*(la|là)\s*(vua|vừa|chuan|chuẩn)\b/.test(plain) && !/(em nghi|nghi la|co le|se hop hon|hop hon|se vua|thu lai|doi chieu)/.test(plain)) return "khang_dinh_size";
  return null;
}

/**
 * The transcript the model reads. Same labels as Desk's level-2 agent (`agent_level2.js`), plus the
 * timestamp, "CŨ" photo tag and session marker of Desk's `leanHistory` — lines without `at` render
 * as before, so older dossiers replay unchanged.
 */
export function renderHistory(history: HistoryLine[], nowIso?: string): string {
  const now = Date.parse(nowIso ?? "") || (history.length > 0 ? Date.parse(history.at(-1)?.at ?? "") : NaN) || Date.now();
  const stamp = (iso: string): string => {
    const d = new Date(iso);
    if (Number.isNaN(d.getTime())) return "";
    const p = (n: number) => String(n).padStart(2, "0");
    return `[${p(d.getDate())}/${p(d.getMonth() + 1)} ${p(d.getHours())}:${p(d.getMinutes())}] `;
  };
  const out: string[] = [];
  let previousAt = NaN;
  for (const line of history) {
    const who = line.who === "khach" ? "KHACH"
      : line.who === "bot" ? "PAGE (bot tu dong — co the sai, khong phai nguon su that)"
      : line.who === "khong_ro" ? "PAGE (chua chac nguoi that go — khong phai nguon su that)"
      : "PAGE (nguoi truc)";
    const at = Date.parse(line.at ?? "");
    if (Number.isFinite(at) && Number.isFinite(previousAt) && at - previousAt >= SESSION_GAP_MS) {
      out.push(`--- PHIEN MOI (cach ${Math.round((at - previousAt) / 3600000)} gio) ---`);
    }
    if (Number.isFinite(at)) previousAt = at;
    const old = Number.isFinite(at) && now - at > OLD_IMAGE_MS ? " CU" : "";
    const images = line.images > 0 ? ` [khach gui ${line.images} anh${old}]` : "";
    const urls = (line.imageUrls ?? []).map((u) => ` [ANH url=${u}]`).join("");
    const note = line.note ? ` [GHI CHU HE THONG: ${line.note}]` : "";
    out.push(`${line.at ? stamp(line.at) : ""}${who}: ${line.text}${images}${urls}${note}`);
  }
  return out.join("\n");
}

export interface SalesAgentOptions {
  model: ChatModelPort;
  logger: Logger;
  clock: Clock;
  /** Test seam for the retry pauses. */
  sleep?: ((ms: number) => Promise<void>) | undefined;
}

export class SalesAgent {
  constructor(private readonly options: SalesAgentOptions) {}

  ready(): boolean {
    return this.options.model.ready();
  }

  /**
   * Whether this pack's rules say a human, not the agent, must take the message.
   *
   * The pattern is ANCHORED IN THE PAST for anything about money (Desk's `PAID_MONEY_RE`, 08/09/2026):
   * `đã/vừa/mới` + a transfer word + a sign of money, or a transfer word followed by `rồi`. A bare
   * `chuyển khoản` used to be enough, which swallowed every QUESTION about paying — "Có cách nào
   * không chuyển khoản cọc vẫn mua được ko em" was reserved for a person and answered with a bare
   * greeting (21/09/2026). Complaint words stay bare: those need a person whatever the tense.
   */
  /**
   * Whether a reply says a person is taking over — the shop must then be notified. The industry's
   * pattern OR tier 1's (24/09/2026: "để em báo bên phụ trách" was not matched by the shoe pack's
   * "nguoi phu trach" alone, and the shop never heard of it).
   */
  static handsOver(pack: IndustryPack, reply: string, chung?: CommonAgent | undefined): boolean {
    const plain = stripDiacritics(reply).toLowerCase();
    for (const pattern of [pack.agent?.handoffReplyPattern ?? "", chung?.handoffReplyPattern ?? ""]) {
      if (pattern !== "" && new RegExp(pattern).test(plain)) return true;
    }
    return false;
  }

  static mustHuman(pack: IndustryPack, message: string, extra: { chung?: CommonAgent | undefined; hoSo?: ShopProfile | null | undefined } = {}): boolean {
    const plain = stripDiacritics(message).toLowerCase();
    for (const pattern of [pack.agent?.mustHumanPattern ?? "", extra.chung?.mustHumanPattern ?? ""]) {
      if (pattern !== "" && new RegExp(pattern).test(plain)) return true;
    }
    // The shop's own topics ("xin biên lai", "xuất hoá đơn"): plain words, matched without accents.
    for (const topic of extra.hoSo?.chuyenNguoi.chuDe ?? []) {
      const words = stripDiacritics(topic).toLowerCase().trim();
      if (words !== "" && plain.includes(words)) return true;
    }
    return false;
  }

  async run(turn: AgentTurn): Promise<AgentOutcome> {
    const started = this.options.clock.now().getTime();
    const trace: AgentTrace[] = [];
    // Every answer the model gave, in order. A replay feeds these back to a scripted model and
    // gets the same turn without calling the gateway (21/09/2026).
    const modelAnswers: ModelAnswer[] = [];
    const knownAmounts = new Set<number>(turn.knownAmounts ?? []);
    const allowedHosts = new Set<string>([hostOf(turn.site), ...(turn.allowedHosts ?? [])].filter(Boolean));
    const budgetAmounts = turn.history.filter((line) => line.who === "khach").flatMap((line) => moneyAmounts(line.text));

    const convo: ChatMessage[] = [
      { role: "system", content: composeSystemPrompt(turn) },
      { role: "user", content: `LICH SU HOI THOAI (cu → moi, tin CUOI la tin can tra loi):\n${renderHistory(turn.history)}\nHay xu ly tin cuoi cua khach.` }
    ];

    // The gateway fails now and then for no reason of ours (an empty answer, a 5xx): one retry per
    // call before the turn gives up (16/09/2026: "mô hình trả về rỗng" left a customer unanswered).
    const sleep = this.options.sleep ?? ((ms: number) => new Promise<void>((resolve) => setTimeout(resolve, ms)));
    const elapsed = () => this.options.clock.now().getTime() - started;
    const deadline = Math.max(5000, Math.min(TURN_DEADLINE_MS, turn.deadlineMs ?? TURN_DEADLINE_MS));
    let modelDown = false;
    const ask = async (): Promise<string | null> => {
      for (let attempt = 1; attempt <= MODEL_ATTEMPTS; attempt += 1) {
        const left = deadline - elapsed();
        if (left < 3000) { modelDown = true; return null; }
        const answer = await this.options.model.complete(convo, { timeoutMs: Math.min(25_000, left) });
        if (answer.ok) { modelAnswers.push({ text: answer.text, model: answer.model }); return answer.text; }
        trace.push({ step: trace.length + 1, error: answer.viSao });
        this.options.logger.warn(`[agent] mo hinh loi lan ${attempt}/${MODEL_ATTEMPTS}: ${answer.viSao}`);
        if (!answer.transient) return null;
        modelDown = true;
        const pause = MODEL_BACKOFF_MS[attempt - 1];
        if (pause === undefined || elapsed() + pause > deadline - 3000) return null;
        await sleep(pause);
      }
      return null;
    };

    // A blocked reply is not the end of the turn (16/09/2026: "cho tôi đôi khác xem" was answered
    // with a price from memory, blocked, and the customer got the rule engine's bare greeting).
    // The model is told WHY and writes again, up to MAX_REVIEW_RETRIES times.
    let reviewRetries = 0;
    const finish = (reply: string, steps: number): AgentOutcome | "retry" => {
      const blocked = reviewReply({ reply, knownAmounts, budgetAmounts, allowedHosts, neverSay: turn.neverSay });
      if (!blocked) return { ok: true, reply: reply.trim(), steps, trace, modelAnswers };
      trace.push({ step: steps, error: `chan: ${blocked}`, blocked: reply });
      this.options.logger.warn(`[agent] cau bi chan (${blocked}): ${redactPII(reply).slice(0, 300)}`);
      if (reviewRetries >= MAX_REVIEW_RETRIES) return { ok: false, viSao: `chan: ${blocked}`, steps, trace, modelAnswers };
      reviewRetries += 1;
      convo.push(
        { role: "assistant", content: JSON.stringify({ reply }) },
        { role: "user", content: `CAU TRA LOI BI CHAN, CHUA GUI KHACH — ly do: ${blocked}. ${REVIEW_HINTS}` }
      );
      return "retry";
    };

    for (let step = 1; step <= MAX_TOOL_STEPS; step += 1) {
      const raw = await ask();
      if (raw === null) return { ok: false, viSao: trace.at(-1)?.error ?? "het_gio", steps: step, trace, modelAnswers, modelDown };
      const parsed = parseAgentJson(raw);
      if (!parsed) {
        trace.push({ step, error: "khong_doc_duoc_json", raw });
        convo.push({ role: "assistant", content: raw }, { role: "user", content: "Output phai la MOT JSON duy nhat theo dung dinh dang. Lam lai." });
        continue;
      }
      if (typeof parsed["reply"] === "string") {
        const done = finish(parsed["reply"], step);
        if (done !== "retry") return done;
        continue;
      }

      const tool = String(parsed["tool"] ?? "");
      const args = (parsed["args"] !== null && typeof parsed["args"] === "object" ? parsed["args"] : {}) as Record<string, unknown>;
      const entry: AgentTrace = { step, tool, args };
      trace.push(entry);
      convo.push({ role: "assistant", content: JSON.stringify(parsed) });
      const result = await this.runTool(tool, args, turn, knownAmounts, allowedHosts);
      entry.result = result;
      convo.push({ role: "user", content: result });
    }

    // Out of steps: make it answer with what it knows.
    convo.push({ role: "user", content: "Da du buoc. Bay gio BAT BUOC tra {\"reply\":\"...\"} dua tren nhung gi da biet, dieu chua chac thi noi se kiem tra sau." });
    const raw = await ask();
    const parsed = raw === null ? null : parseAgentJson(raw);
    if (!parsed || typeof parsed["reply"] !== "string") return { ok: false, viSao: raw === null ? (trace.at(-1)?.error ?? "het_gio") : "het_buoc_khong_tra_loi", steps: MAX_TOOL_STEPS + 1, trace, modelAnswers, modelDown: raw === null && modelDown };
    const done = finish(parsed["reply"], MAX_TOOL_STEPS + 1);
    return done === "retry" ? { ok: false, viSao: "het_buoc_sau_khi_bi_chan", steps: MAX_TOOL_STEPS + 1, trace, modelAnswers } : done;
  }

  private async runTool(tool: string, args: Record<string, unknown>, turn: AgentTurn, knownAmounts: Set<number>, allowedHosts: Set<string>): Promise<string> {
    try {
      if (turn.agent.tools.length > 0) {
        const matching = turn.agent.tools.find((t) => t.name === tool);
        if (matching) {
          if (matching.handler === "landing") {
            let resultStr = "";
            if (matching.landingMethod === "findStock") {
              const result = await turn.tools.findStock(args);
              if (matching.tracksAmounts) numbersIn(result, knownAmounts);
              if (matching.tracksLinks) {
                for (const m of JSON.stringify(result).matchAll(/https?:\/\/[^\s"\\]+/g)) {
                  const host = hostOf(m[0]);
                  if (host) allowedHosts.add(host);
                }
              }
              resultStr = JSON.stringify(result).slice(0, STOCK_RESULT_CHARS);
            } else if (matching.landingMethod === "policy") {
              const result = await turn.tools.policy();
              if (matching.tracksAmounts) numbersIn(result, knownAmounts);
              resultStr = result.slice(0, TEXT_RESULT_CHARS);
            } else if (matching.landingMethod === "bankAccount") {
              resultStr = JSON.stringify(await turn.tools.bankAccount());
            }
            return `KET QUA ${tool}:\n${resultStr}`;
          }
          if (matching.handler === "static") {
            return `KET QUA ${tool}:\n${fillAgentText(matching.staticText || "", fillValuesOf(turn)).slice(0, TEXT_RESULT_CHARS)}`;
          }
          if (matching.handler === "disabled") {
            return `KET QUA ${tool}: ${matching.disabledMessage || ""}`;
          }
        }
      }

      if (tool === "tra_kho") {
        const result = await turn.tools.findStock(args);
        numbersIn(result, knownAmounts);
        // Links the finder returned are the shop's own pages.
        for (const m of JSON.stringify(result).matchAll(/https?:\/\/[^\s"\\]+/g)) { const host = hostOf(m[0]); if (host) allowedHosts.add(host); }
        return `KET QUA tra_kho:\n${JSON.stringify(result).slice(0, STOCK_RESULT_CHARS)}`;
      }
      if (tool === "chinh_sach") {
        const policy = await turn.tools.policy();
        numbersIn(policy, knownAmounts);
        return `KET QUA chinh_sach:\n${policy.slice(0, TEXT_RESULT_CHARS)}`;
      }
      if (tool === "tai_khoan_shop") return `KET QUA tai_khoan_shop:\n${JSON.stringify(await turn.tools.bankAccount())}`;
      return "Cong cu khong ton tai. Chi dung cac cong cu da cho hoac {\"reply\":...}.";
    } catch (error) {
      const message = error instanceof Error ? error.message : String(error);
      this.options.logger.warn(`[agent] cong cu ${tool} loi: ${message}`);
      return `KET QUA ${tool}: LOI — ${message}. Khong duoc bia; noi se kiem tra roi bao lai.`;
    }
  }

}

/** The placeholder values of one turn: site, shop name, and the profile (empty when the shop has none). */
export function fillValuesOf(turn: AgentTurnInput): FillValues {
  return { site: turn.site, tenShop: turn.shopName ?? turn.site, hoSo: turn.hoSo ?? emptyShopProfile() };
}

/** The tool protocol, generated from the pack's tool list: one JSON per step, `reply` when done. */
export function renderToolProtocol(turn: AgentTurnInput): string {
  const values = fillValuesOf(turn);
  const lines = turn.agent.tools.map((t, i) => `${i + 1}. ${fillAgentText(t.moTa, values)}`);
  return [
    "## CONG CU (moi luot chi goi MOT cong cu, tra ve JSON thuan tuy khong markdown)",
    ...lines,
    "Khi DA DU thong tin: {\"reply\":\"cau tra loi gui khach\"}.",
    "Tra loi CHI bang mot JSON duy nhat moi luot."
  ].join("\n");
}

/**
 * The exact `system` message the model is given, in tier order: tier 1 (the platform), tier 2 (the
 * industry, as this shop runs it), tier 3 (the shop profile), what the shop taught and what the
 * photo showed, then WHAT THE SYSTEM CAN DO (which wins over everything above), then the tool
 * protocol. Exported because the dossier stores the RESOLVED prompt: a pack edited next week must
 * not change what last week's turn is shown to have used.
 */
export function composeSystemPrompt(turn: AgentTurnInput): string {
  const values = fillValuesOf(turn);
  const parts: string[] = [];
  if (turn.chung && turn.chung.khoi.length > 0) parts.push(renderBlocks(turn.chung.khoi, values));
  parts.push(renderBlocks(blocksForShop(turn.agent.khoi, values.hoSo), values));
  parts.push(renderProfile(turn.hoSo, turn.chinhSach));
  parts.push(turn.extraContext ?? "");
  if (turn.nangLuc && turn.nangLuc.length > 0) {
    parts.push(["## NANG LUC HE THONG LUOT NAY (GHI DE moi luat o tren khi mau thuan)", ...turn.nangLuc.map((l) => `- ${fillAgentText(l, values)}`)].join("\n"));
  }
  if (turn.agent.tools.length > 0) parts.push(renderToolProtocol(turn));
  return parts.filter((part) => part.trim() !== "").join("\n\n");
}

/**
 * The capability lines for one turn, from what is actually open and running. Every line here used
 * to be a hand-written sentence in the industry pack, which is how the pack kept saying "chưa xem
 * được ảnh" after Xeon had started reading photos.
 */
export function systemCapabilities(input: { open: readonly string[]; visionReady: boolean; hoSo?: ShopProfile | null | undefined; chaoAi?: boolean | undefined; guiKem?: boolean | undefined }): string[] {
  const lines: string[] = [];
  // Giai đoạn 7: the landing prepends its own greeting to the opening reply — the agent must not greet again.
  if (input.chaoAi === true) lines.push("HE THONG TU CHEN CAU CHAO dau hoi thoai TRUOC cau nay: KHONG tu chao (\"Dạ em nghe ạ\", \"chào bác\"...), vao thang noi dung tra loi.");
  if (input.guiKem === true) lines.push("HE THONG TU GUI THE ANH cua toi da 2 ma ban NEU TEN/MA trong cau tra loi — KHONG noi \"khong gui duoc anh\", KHONG bao khach bam link de xem anh; neu khach xin anh thi neu ma va noi \"em gửi ảnh mẫu bên dưới\".");
  if (input.open.includes("order.formLink")) lines.push("PHIEU DAT HANG do HE THONG tu gui kem khi khach chot du mau + size con hang (theo ho so shop): KHONG tu ghep link phieu, chi xac nhan mau + size + gia roi noi phieu se gui kem.");
  lines.push(input.visionReady
    ? "ANH KHACH GUI: he thong DA doc anh truoc luot va ghi ket qua o dong \"ẢNH KHÁCH GỬI\" (neu doc duoc). KHONG co dong do = khong doc duoc: khong doan mau, xin ten mau hoac ma tren tem/hop."
    : "CHUA xem duoc anh. Tin co \"[khach gui N anh]\" → KHONG doan mau trong anh; xin khach ten mau hoac ma tren tem/hop.");
  lines.push("He thong KHONG tu gui anh the san pham hay anh huong dan do chan. KHONG noi \"em gửi ảnh bên dưới\". Muon khach xem mau → gui LINK trang san pham lay tu tra_kho.");
  const khiChot = input.hoSo?.banHang.khiChot ?? "";
  if (khiChot === "phieu") {
    lines.push("KHACH CHOT (da co mau + size con hang): gui PHIEU DAT HANG = link trang san pham tu tra_kho, them ?size=<size khach chon> vao cuoi link. Khach dien thong tin nhan hang tren phieu, he thong tu hien ma QR chuyen khoan. Noi: \"Dạ em gửi phiếu đặt hàng, {khach} điền giúp em thông tin nhận hàng, xong hệ thống tự ra mã QR để {khach} chuyển khoản ạ.\" KHONG tu xin ten/SDT/dia chi de go don.");
  } else if (khiChot === "goi-nguoi") {
    lines.push("KHACH CHOT: KHONG gui phieu, KHONG xin dia chi. Noi: \"Dạ phần này để em gọi người phụ trách vào lên đơn cho {khach} ngay ạ.\"");
  }
  // 25/09/2026: a landing that opens `order.lookup` has its orders looked up BEFORE the turn (the
  // VAN_DON / DON_DOI_SIZE blocks of the note); the agent still never invents an order's state.
  lines.push(input.open.includes("order.lookup")
    ? "DON HANG / VAN DON: he thong DA tra don theo SDT khach cho va ghi ket qua o khoi \"VAN DON CUA KHACH\" / \"DON CUA KHACH\" trong ghi chu (neu co). KHONG co khoi do = chua tra duoc: xin SDT dat don, noi em kiem tra roi bao lai; KHONG bia trang thai don, KHONG tu ghep link tra cuu."
    : "KHONG tra duoc don hang / van don / tinh trang don trong luot nay. Khach hoi don, van don, doi size don da dat → xin SDT dat don va noi em goi nguoi phu trach kiem tra; KHONG bia trang thai don.");
  if (!input.open.includes("policy.get") && !input.open.includes("shop.profile")) lines.push("Landing chua mo chinh sach: KHONG noi chinh sach, goi nguoi phu trach.");
  lines.push("Ngoai link trong ket qua tra_kho, link loc {site}/?... va link phieu dat hang, KHONG gui link nao khac.");
  return lines;
}
